version: "3.3"
services:
  depository-ums:
    container_name: dn-ums
    image: node
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - MONGODB_CONNECTION_STRING=mongodb://mongo:27017/ums
    ports:
      - 3000:3000
      - 9229:9229
      - 4200:4200
    networks:
      - depository-net
    depends_on:
      - mongo
    command: npm run debug
    
  mongo:
    container_name: dn-mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    networks:
      - depository-net

networks:
  depository-net: